<?php

/**
* @file
* Display a Adema Importation formulaire
*/

function siit_importation_paf_03_menu(){
    $items = array();
    $items['siit_importation_paf_03'] = array(
        'title'            => t('Importation des données de la PAF Ivato'), 
        'page callback'    => 'drupal_get_form',
        'page arguments' => array('siit_importation_paf_03_form'),
        'access arguments' => array('access siit_importation_paf_03'),
        'type'             => MENU_LOCAL_TASK,
    	//'access callback' => TRUE,
    );
    
    return $items;
    
}  

function siit_importation_paf_03_permission() {
  return array( 
    'access siit_importation_paf_03' => array(
      'title' => t('siit_importation_paf_03 : paf03 importation formulaire'),
      'description' => t('Perform administration tasks for paf01 importation.'),
    ),
  );
}

function siit_importation_paf_03_form($form, &$form_state) {

	if(!isset($form_state['storage']['confirm'])){
		return get_siit_importation_paf_03_form($form, $form_state);
    } else {
    		
    		$file = file_load($form_state['values']['csv_file']);
    		$filename = $file->filename;
    		
    		//Si on sait qu'il existe un import avec statut diff de validé, on vérifie si il en existe un qui est à valider !
    		list($id_importation,$question) = searchFileExist($filename, STATUT_AVALIDER, false);
		
		if($id_importation){
            	//Si il en existe un à valider, on va poser la question
			drupal_get_messages('error'); //Reset les messages
			$path = 'siit_importation_paf_03';
			$description = '';
			$yes = 'Oui';
			$no = 'Non';
			$form = confirm_form($form, $question, $path, $description, $yes, $no);
			$form['csv_file'] = array('#type' => 'hidden', '#value' => $_POST['csv_file']);
			$form['chemin'] = array('#type' => 'hidden', '#value' => $form_state['storage']['uri']);
			$form['aeroport'] = array('#type' => 'hidden', '#value' => $form_state['values']['aeroport']);
			$form['filename'] = array('#type' => 'hidden', '#value' => $filename);
			$form['actions']['submit'] = array(
			    '#type' => 'submit',
			    '#value' => $yes,
			    '#attributes' => array('class' => array('button button--primary js-form-submit form-submit btn-success btn'),),
			    '#submit' => array('csv_import_paf_03_submit'),
			 );  
			 $form['#attached']['css'] = array(drupal_get_path('module', 'siit_importation_paf_03') . '/css/paf03.css');
 			 return $form;
        } else {
        		csv_import_paf_03_submit($form, $form_state);
        	}
	}
        
	
	
}

function get_siit_importation_paf_03_form($form, &$form_state){
	drupal_set_title(t('Importation des données de la PAF Ivato'));
	$options = get_all_pays(false, 'paf01');
	

	$form["aeroport"] = array(
	    "#type" => "select",      
	    "#title" => t("Aéroport d'arrivée :"),
	    "#options" => get_all_aeroport(false,1),
	    "#default_value" => "1",
	    "#required" => TRUE,
	    );
		
		
	$form['importation']["template"] = array(
	    "#markup" => "Cliquez ici pour télécharger un exemple de <a href='sites/default/files/templates/SIIT_PAF_01.csv' target='_blank'>template</a>. Merci de suivre la procédure d'export du fichier ACCESS en UTF-8.",      
	    );
	    
	$form['importation']['csv_file'] = array(
	        '#title' => 'Importer Fichier', // Titre dans la page d'importation du fichier
	        '#description' => 'Seuls ces fichiers csv en utf-8 sont valides.',
	        '#type' => 'managed_file',
	        '#required' => TRUE,
	        '#upload_validators' => array(
	            'file_validate_extensions' => array('csv'),
	        ),
	    );
	    
	 $form['importation']['submit'] = array(
	        '#type' => 'submit',
	        '#value' => t('Process'),
	        '#attributes' => array('class' => array('button button--primary js-form-submit form-submit btn-success btn'),),
	        //'#validate' => array('csv_import_paf_03_validate'),
	    		'#submit' => array('csv_import_paf_03_submit'),
	    		
	    );
	    
	    
	 $form['importation']['back'] = array('#type' => 'submit', '#value' => t('Retour'));
   	 $form['importation']['back']['#submit'] = array('siit_back_submit_03');
	 $form['importation']['back']['#limit_validation_errors'] = array();
	 $form['importation']['back']['#name'] = 'back';
	 $form['#attributes']['class'][] = 'import-form';
	 return $form;
}

function csv_import_paf_03_validate($form, &$form_state) {
	$file = file_load($form_state['values']['csv_file']);
	$filename = $file->filename;
	//Controle si un import validé existe déjà
	//list($id_importation,$question) = searchFileExist($filename, STATUT_VALIDE, false);
	
}

function siit_back_submit_03($form, &$form_state)  {
	$form_state['redirect'] = array(
		'siit_importation_liste',
		array(),
		302,
  );
}

function csv_import_paf_03_submit($form, &$form_state){
	
	if(!isset($form_state['storage']['confirm'])) {
		$file = file_load($form_state['values']['csv_file']);
    		$filename = $file->filename;
    		//Vérifie si existe avec un statut diff de valide
    		list($id_importation,$question) = searchFileExist($filename, STATUT_VALIDE, true);
        
        if($id_importation){
        		//Si oui, on va repartir sur le form initial
        		$form_state['storage']['confirm'] = TRUE;
            $form_state['rebuild'] = TRUE;
            $form_state['storage']['csv_file'] = $form_state['values']['csv_file'];
            $file = file_load($form_state['values']['csv_file']);
            $form_state['storage']['uri'] = $file->uri;
        } else {
        		$file = file_load($form_state['values']['csv_file']);
        		$aeroport = $form_state['values']['aeroport'];
        		$filename = $file->filename;
            traitement_paf_03($file->uri,$form_state, $aeroport, $filename);
        }
    } else {
        if(isset($_POST["chemin"])) {
        		$chemin = $_POST["chemin"];
        		$aeroport = $_POST['aeroport'];
        		$filename = $_POST['filename'];
        } else{
            $file = file_load($form_state['values']['csv_file']);
            $filename = $file->filename;
            $chemin = $file->uri;
            $aeroport = $form_state['values']['aeroport'];
        }
        traitement_paf_03($chemin,$form_state, $aeroport, $filename);
    }


}

function traitement_paf_03($chemin,$form_state, $id_aeroport_arrivee, $filename) {
	
	$valid = true;
	$uri = $chemin;
    
   
    $handle = fopen(drupal_realpath($uri), 'r') or die(t('Unable to open the temp file.'));
    $i = 0;
    $error = false;
   
   
   
    $firstData = fgetcsv($handle, 0, ';');
    
    if (count($firstData) == 13) {
    		$delimiterLine = ";";
    } else {
	    	$handle = fopen(drupal_realpath($uri), 'r') or die(t('Unable to open the temp file.'));
	    	//$firstData = fgetcsv($handle, 0, ',', '"');
	    	$firstData = fgetcsv($handle, 0, ',');
	    	if (count($firstData) == 13) {
	    		$delimiterLine = ";";
			} else {
			 	//Pour la première ligne, on vérifie que l'en-tête est incorrecte
			 	drupal_set_message(t("Fichier non conforme!"), $type = 'error', $repeat = FALSE);
				$valid=false;
				return;
			}
    }

    $id = str_replace('"','',$firstData[0]); $id = (string)$id;
    
    if ( $id != $id) {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'id'. (Col 1)"), $type = 'error', $repeat = FALSE);
    }
    
    if ($firstData[1] != 'civilite') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'civilite'. (Col 2)"), $type = 'error', $repeat = FALSE);
    }
    
    if ($firstData[2] != 'nationalite') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'nationalite'. (Col 3)"), $type = 'error', $repeat = FALSE);
    }
    
    if ($firstData[3] != 'dat_naiss') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'dat_naiss'. (Col 4)"), $type = 'error', $repeat = FALSE);
    }
    
    //GSE 22/06/2018 : n'est plus dans le fichier de johan
    /*if ($firstData[4] != 'lieu_naiss') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'lieu_naiss'. (Col 5)"), $type = 'error', $repeat = FALSE);
    }*/
	
	if ($firstData[4] != 'profession') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'profession'. (Col 5)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[5] != 'numvol') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'numvol'. (Col 6)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[6] != 'compavol') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'compavol'. (Col 7)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[7] != 'provenance_vol') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'Provenance'. (Col 8)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[8] != 'dat_arr') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'dat_arr'. (Col 9)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[9] != 'pays') {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'pays'. (Col 10)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[10] != "hebergement") {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'hebergement'. (Col 11)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[11] != "dat_retor") {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'dat_retor'. (Col 12)"), $type = 'error', $repeat = FALSE);
    }
	
	if ($firstData[12] != "objvoyag") {
	    	$error = true;
	    	drupal_set_message(t("Mauvaise entete 'objvoyag'. (Col 13)"), $type = 'error', $repeat = FALSE);
    }
	
    /*0 Titre_Civilité;
	1 Nom;
	2 Prénoms;
	3 Nom_de_jeune_fille;
	4 Date_de_naissance;
	5 Lieu_de_naissance;
	6 Nationalit‚;
	7 Profession;
	8 Num‚ro_du_passeport;
	9 Date_de_d‚livrance_passeport;
	10 Fin_de_validit‚_passeport;
	11 Lieu_d'‚mission_passeport;
	12 Nombre_d'enfants;
	13 Enfant_1;
	14 Enfant_2;
	15 Enfant_3;
	16 Enfant_4;
	17 Num‚ro_du_vol;
	18 Compagnie;
	19 Date_du_vol;
	20 Date_de_retour;
	21 Num‚ro_du_visa;
	22 Visa_d‚livr‚_…;
	23 Visa_d‚livr‚_le;
	24 Autorit‚_‚metteur;
	25 Dur‚e_du_s‚jour(mois);
	26 Dur‚e_du_s‚jour(jours);
	27 A‚roport_d'embarquement;
	28 Lieu_de_r‚sidence;
	29 Adresse;
	30 Ville;
	31 Pays;
	32 En_transit;
	33 Lieu_de_destination;
	34 A‚roport_de_destination;
	35 Date_de_d‚part;
	36 Voyage_en_groupe;
	37 Objet_du_voayage;
	38 H‚bergement    */
	
    $data = array();
    $i=1;
   
   
    if (!$error) {
		while(($line = fgetcsv($handle, 0, $delimiterLine, '"')) !== FALSE) {
		
				// VERIFICATION DONNEES	
				
				//"d/m/Y H:i:s"
				if (empty($line[3]) || $line[3] == '00') {
					$line[4] = '01/01/1980';
				}
				
				if (!empty($line[3])) {
					$line[3] = formatDate($line[3]); //DDN
					if(!validateDate($line[3],"d/m/Y")){
						drupal_set_message(t("Date naissance non conforme! '".$line[3]."' Ligne ".$i), $type = 'error', $repeat = FALSE);				
						$valid = false;				
				    }else  {
						 $date_naiss =  substr($line[3],6,4)."-".substr($line[3],3,2)."-".substr($line[3],0,2)." ".substr($line[3],11,8);
					}
				} else $date_naiss = "1980-01-01";
				
				
				
	
				$id_civilite = get_id_civilite($line[1]);
				if(!$id_civilite){
					//drupal_set_message(t("La civilité '".$line[0]."' est introuvable dans la base."." Ligne ".$i), $type = 'error', $repeat = FALSE);				
					//$valid = false;
					//On ne va pas bloquer
					$id_civilite = 1;
				}
				
			    //$id_pays_embarquement = get_id_pays_embarquement_03($line[7]);
			    $id_pays_embarquement = get_id_pays($line[7], ENTITE_PAF01);
				if(!$id_pays_embarquement)
				{
					$id_pays_embarquement=0;
				}
				
				if (trim($line[2]) == 'v' ||  trim($line[2]) == 'V') {
					$line[2] = 'Inconnu';
				}
				
				$id_nat = get_id_nationalite(trim($line[2]),ENTITE_PAF01);
				if(!$id_nat && !empty($line[2])){
					drupal_set_message(t("La nationalité '".clean_ms_word(utf8_encode($line[2]))."' est introuvable dans la base."." Ligne ".$i), $type = 'error', $repeat = FALSE);
					$valid = false;
				}
				
				if ($line[10] == '' || trim($line[10]) == '=' || trim($line[10]) == '22/5' || trim($line[10]) == 'v' || trim($line[10]) == 'V' || trim($line[10]) == 'a') {
					$line[10] = 'INCONNU';
				}
				
				if (empty(trim($line[9]))) {
					//Prendre la nationalité
					$line[9] = trim($line[2]);
				}
				
				$id_pays = get_id_pays(trim($line[9]),ENTITE_PAF01);
				if(!$id_pays){
					drupal_set_message(t("Le pays '".clean_ms_word(utf8_encode($line[9]))."' est introuvable dans la base."." Ligne ".$i), $type = 'error', $repeat = FALSE);
					$valid = false;				
				}
	  	
				
				$id_heb = get_id_hebergement($line[10]);
				if(!$id_heb){
					//drupal_set_message(t("L'hébergement '".utf8_encode($line[38])."' est introuvable dans la base."." Ligne ".$i), $type = 'error', $repeat = FALSE);
					//$valid = false;
					$id_heb = 4; //Hotel			
				}
				
				$id_obj_voyage = get_id_obj_voyage($line[10]);
				if(!$id_obj_voyage){
					$id_obj_voyage	= 1;//Tourisme
				}
				
				
				$id_profession = get_id_profession($line[4]);
				
				//remplir le data array pour la sauvegarde
				if($valid){	
					
					
					$str_date = explode("/", substr($line[8],0,10));
					$annee = $str_date[2];
					$mois = $str_date[1];
					$jour = $str_date[0];
					$datevol = $annee.'-'.$mois.'-'.$jour;
					$datevol = date_create($datevol);
					$datevol = date_format($datevol,'Y-m-d');
					//drupal_set_message(t("$str_date[0], $str_date[1], $str_date[2]"), $type = '', $repeat = true);
					
					if (!empty($line[11])) {
						$line[12] =  formatDate($line[11]);
						$dt_retour = substr($line[11],6,4)."-".substr($line[11],3,2)."-".substr($line[11],0,2)." ".substr($line[11],11,8);
					} else {
						//On fige la date du retour au 28 du mois
						$dt_retour = $annee."-".$mois."-28";
					}
									
					$cd_mois = get_cd_mois($mois);
					//$dt_vol = $annee."-".$cd_mois."-01";
					
					$dt_vol = $datevol ;
					$data[] = array(
						'id_civilite' =>  $id_civilite,
						'is_resident' => '0',
						'id_nationalite' => $id_nat,
						'dt_naissance' => $date_naiss,
						'lieu_naissance' => '',
						'id_pays' => $id_pays,
						//'lieu_residence' => $line[28],
						//'is_voyage_groupe' => $line[36] == ' ' ? $line[36] : '0',
						//'is_transit' => $line[32] == ' ' ? $line[32] : '0',
						'lieu_residence' => '', 
						'is_voyage_groupe' => '0',
						'is_transit' => '0',
						'li_lieu_destination' => 'Antananarivo',
						'id_profession' => $id_profession,
						'dt_vol' => $dt_vol,
						'dt_retour' => $dt_retour,
						'id_hebergement' => $id_heb,
						'id_objet_voyage' => $id_obj_voyage,
						'id_pays_embarquement' => $id_pays_embarquement,
						'id_aeroport_arrivee' => $id_aeroport_arrivee,
					);
				}	
				//drupal_set_message(t("i=".$i.", valeur data 'li_lieu_destination'".$data[$i]["li_lieu_destination"]), $type = '', $repeat = FALSE);
	        $i++;
	        
	    }
	    fclose($handle);
	    
		
		//UPDATE AND SAVE	 
		if(!$valid){
			//drupal_set_message(t("Arret processus !"), $type = 'errors', $repeat = FALSE);
			header("Refresh:0");
		}
		else{
			
			//INSERTION siit_importation		
			// rechecher importation avec dt_import et li_fichier et id_type_fichier
			$data_import = array();
			$data_import['annee'] = $annee;
			$data_import['id_mois'] = $mois;
			$data_import["li_fichier"] = $filename;
			$data_import["id_statut"] = STATUT_AVALIDER;
			$data_import["id_type_fichier"] = TYPE_FICHIER_PAF01;
			
			//On supprime l'importation existante pour l'équivalent
			controleDoublonImportation(0, 0, ENTITE_PAF01, $data_import["li_fichier"]); 
			$id_importation = insert_importation($data_import);
		
			// INSERTION siit_passager
			foreach ($data as $value) {
			 insert_passager_paf_01($value,$id_importation);			
			}
			
			drupal_set_message("L'import a été effectué avec succès.", $type = 'status');
			$form_state['redirect'] ="siit_importation_liste";
		}	
	}
}

function insert_passager_paf_03($value,$id_importation){
			if (!empty($value["lieu_naissance"]) && !empty($value["id_nationalite"]) 
				&& !empty($value["id_pays"])) {
				db_insert('siit_passager')
				->fields(array('id_civilite', 'is_resident', 'id_nationalite', 
							'dt_naissance', 'lieu_naissance', 'id_pays', 'lieu_residence',
							'is_voyage_groupe', 'is_transit', 'id_vol', 'id_profession',
							'id_compagnie', 'li_lieu_destination', 'dt_vol', 'dt_retour', 'id_hebergement', 
							'id_objet_voyage', 'id_importation', 'id_pays_embarquement', 'id_aeroport_arrivee'))
				->values(array(							
		            'id_civilite' => $value["id_civilite"],
		        	'is_resident' => $value["is_resident"],
		            'id_nationalite' => $value["id_nationalite"],
		        	'dt_naissance' => $value["dt_naissance"],
		            'lieu_naissance' => $value["lieu_naissance"],
		        	'id_pays' => $value["id_pays"],
		            'lieu_residence' => $value["lieu_residence"],
		        	'is_voyage_groupe' => $value["is_voyage_groupe"],
		        	'is_transit' => $value["is_transit"],
		            'id_vol' => null,
		            'id_profession' => $value["id_profession"],
		        	'id_compagnie' => null,
		            'li_lieu_destination' => $value["li_lieu_destination"],
		        	'dt_vol' => $value["dt_vol"],
		            'dt_retour' => $value["dt_retour"],
		        	'id_hebergement' => $value["id_hebergement"],
		            'id_objet_voyage' => $value["id_objet_voyage"],
					'id_importation' => $id_importation,
					'id_pays_embarquement' => $value["id_pays_embarquement"],
					'id_aeroport_arrivee' => $value["id_aeroport_arrivee"],))
				->execute();	
				}
}	