<?php

/**
* @file
* Display a Adema Importation formulaire
*/

	function siit_bcm_menu(){
    $items = array();
    $items['siit_bcm'] = array(
        'title'            => t('Formulaire BCM'), 
        'page callback'    => 'drupal_get_form',
        'page arguments' => array('siit_bcm_form'),
        'access arguments' => array('access siit_bcm'),
        'type'             => MENU_LOCAL_TASK,
    		//'access callback' => TRUE,
    );
    
    return $items;
    
}  

function siit_bcm_permission() {
  return array( 
    'access siit_bcm' => array(
      'title' => t('siit_bcm : bcm formulaire'),
      'description' => t('Perform administration tasks for bcm.'),
    ),
  );
}

function siit_bcm_form($form, &$form_state) {
	
	   drupal_set_title(t('Formulaire BCM'));
	
	
		if(!isset($form_state['storage']['confirm'])){	
	        return get_siit_bcm_form($form,$form_state);
	    }
        else{
		
		    list($id_importation,$question) = searchDataExist(ENTITE_BCM, $_POST['annee'], $_POST['mois'], STATUT_AVALIDER, false);
			
			if($id_importation){
			
					$recettedollars = $form_state['values']['recettedollars'] ;
					$recetteeuro = $form_state['values']['recetteeuro'] ;
					$recetteariary = $form_state['values']['recetteariary'] ;
					$recettedts = $form_state['values']['recettedts'] ;
					$nb_touristes = $form_state['values']['nb_touristes'] ;
			
					$path = 'siit_bcm';
					$description = '';
					$yes = 'Oui';
					$no = 'Non';
					  $form = confirm_form($form, $question, $path, $description, $yes, $no);
					  $form['annee'] = array('#type' => 'hidden', '#value' => $_POST['annee']);
					  $form['mois'] = array('#type' => 'hidden', '#value' => $_POST['mois']);
					  $form['recettedollars'] = array('#type' => 'hidden', '#value' => $recettedollars);
					  $form['recetteeuro'] = array('#type' => 'hidden', '#value' => $recetteeuro);
					  $form['recetteariary'] = array('#type' => 'hidden', '#value' => $recetteariary);
					  $form['recettedts'] = array('#type' => 'hidden', '#value' => $recettedts);
					  $form['nb_touristes'] = array('#type' => 'hidden', '#value' => $nb_touristes);					  
					  $form['actions']['submit'] = array(
						'#type' => 'submit',
						'#value' => $yes,
						'#attributes' => array('class' => array('button button--primary js-form-submit form-submit btn-success btn'),),
						'#submit' => array('siit_bcm_form_submit'),
					  );  
					  $form['#attached']['css'] = array(
						  drupal_get_path('module', 'siit_bcm') . '/css/bcm.css'
					  );
					  return $form;
			}
			else siit_bcm_form_submit($form,$form_state);
		}
	
	
	
}


function get_siit_bcm_form($form, &$form_state){
	 
    $form['annee'] = array(
	    "#type" => "select",      
	    "#title" => t("Année :"),
	    "#options" => optionYear(),
	    //"#default_value" => $settings[""],
	    "#required" => TRUE,
		);
	
	$form["mois"] = array(
	    "#type" => "select",      
	    "#title" => t("Mois :"),
	    "#options" => optionMonth(false),
	    "#required" => TRUE,
	    //"#description" => t("La ville de depart de la carte ?"),
	    );	
	
	$form['nb_touristes'] = array(
		'#title' => t('Nombre de touristes dans le mois :'),
		'#type' => 'textfield',
		"#required" => true,
		);
    
	$form['recettedollars'] = array(
		'#title' => t('Recettes touristiques en Dollars :'),
		'#type' => 'textfield',
		"#required" => true,
		);
		
	$form['recetteeuro'] = array(
		'#title' => t('Recettes touristiques en Euros :'),
		'#type' => 'textfield',
		"#required" => TRUE,
		);
		
	$form['recetteariary'] = array(
		'#title' => t("Recettes touristiques en millions d'Ariary :"),
		'#type' => 'textfield',
		"#required" => TRUE,
		);
		
	$form['recettedts'] = array(
		'#title' => t('Recettes touristiques en DTS :'),
		'#type' => 'textfield',
		"#required" => TRUE,
		);
    
	    
	 $form['importation']['submit'] = array(
	        '#type' => 'submit',
	        '#value' => t('Enregistrer'),
	        '#attributes' => array('class' => array('button button--primary js-form-submit form-submit btn-success btn'),),
			'#validate' => array('siit_bcm_form_validate'),
	    		'#submit' => array('siit_bcm_form_submit'),
	    );
	    	
	    
	  $form['importation']['back'] = array('#type' => 'submit', '#value' => t('Retour'));
	  $form['importation']['back']['#submit'] = array('siit_back_submit');
	  $form['importation']['back']['#limit_validation_errors'] = array();
	  $form['importation']['back']['#name'] = 'back';
	
	return $form;
}

function siit_bcm_form_validate($form, &$form_state){

		//Test deja validé
		if(!empty($_POST['annee']) && !empty($_POST['mois'])){
			//Controle si un import validé existe déjà
			list($id_importation,$question) = searchDataExist(ENTITE_BCM, $_POST['annee'], $_POST['mois'], STATUT_VALIDE, false);
		}
		
		
		$nb_touristes = $form_state['values']['nb_touristes'];
		if(!is_numeric($nb_touristes)){
		    form_set_error('edit-nb-touristes', t("Le nombre de touristes '$nb_touristes' n'est pas un entier."));
		}
		
		$recette_dollar = $form_state['values']['recettedollars'];
		if(!is_numeric($recette_dollar)){
		    form_set_error('edit-dollars', t("La recette en Dollar '$recette_dollar' n'est pas un entier."));
		}
		
		
		$recette_euro = $form_state['values']['recetteeuro'];
		if(!is_numeric($recette_euro)){
		    form_set_error('edit-euro', t("La recette en Euro '$recette_euro' n'est pas un entier."));
		}
		
		$recette_ariary = $form_state['values']['recetteariary'];
		if(!is_numeric($recette_ariary)){
		    form_set_error('edit-ariary', t("La recette en Ariary '$recette_ariary' n'est pas un entier."));
		}
		
		$recette_dts = $form_state['values']['recettedts'];
		if(!is_numeric($recette_dts)){
		    form_set_error('edit-dts', t("La recette DTS '$recette_dts' n'est pas un entier."));
		}
}

function siit_bcm_form_submit($form,&$form_state){  

		$data = array();
		
		$data['annee'] = $_POST['annee'];
		$data['id_mois'] = $_POST['mois'];
		
		$data['recette_dollar'] = $form_state['values']['recettedollars'];
		$data['recette_euro'] = $form_state['values']['recetteeuro'];
		$data['recette_ariary'] = $form_state['values']['recetteariary'];
		$data['recette_dts'] =  $form_state['values']['recettedts'];
		$data['nb_touristes'] =  $form_state['values']['nb_touristes'];

		if(!isset($form_state['storage']['confirm'])) {
			
			list($id_importation,$question) = searchDataExist(ENTITE_BCM, $_POST['annee'], $_POST['mois'], STATUT_VALIDE, true) ;
		
			if($id_importation){
				$form_state['storage']['confirm'] = TRUE;
				$form_state['rebuild'] = TRUE;
			} else {
				bcm_save($form_state,$data);
			}
		} else {
				bcm_save($form_state,$data);
		}
				
			
}

function bcm_save(&$form_state,$data){

		
		$data_import = array();
		$data_import['annee'] = $data['annee'];
		$data_import['id_mois'] = $data['id_mois'];
		$data_import['li_fichier'] = "";//basename($path);
		$data_import['id_statut'] = STATUT_AVALIDER;
		$data_import['id_type_fichier'] = TYPE_FICHIER_BCM;
		
		
		//On supprime l'importation existante pour l'équivalent
		controleDoublonImportation($data_import['annee'], $data_import['id_mois'],ENTITE_BCM, $data_import["li_fichier"]); //NON PAS POUR PAF01
		$id_importation = insert_importation($data_import);
		$data["id_importation"] = $id_importation;
		
		/*drupal_set_message(t("Dans data :".$data['annee'].",".$data['id_mois'].",".$data['recette_dollar'].",".$data['recette_euro'].
					",".$data['recette_ariary'].",".$data['recette_dts'].",".$data['id_importation'].""), $type = '', $repeat = true);*/
		
		$sql = "select id_recette_touristique from siit_recette_touristique where annee = ".$data['annee']." and id_mois = ".$data['id_mois']."";
		$result = db_query($sql);
		
		$id_recette_touristique = 0;
		foreach($result as $u){
		   $id_recette_touristique = $u->id_recette_touristique;
		}
		
		if($id_recette_touristique){		  
			$query = db_update('siit_recette_touristique')
			->condition('id_recette_touristique', $id_recette_touristique);
		}
		else{	
			$query = db_insert('siit_recette_touristique');
		}
		$query
		  ->fields($data)
		  ->execute();
		
		
		drupal_set_message("L'import a été effectué avec succès.", $type = 'status');
		$form_state['redirect'] = "siit_importation_liste";	

}

function get_li_mois($id_mois){

	$li_mois ="";
	$sql = "SELECT li_mois FROM {siit_mois} p WHERE 
			p.id_mois = ".$id_mois.""; 
		
	$results = db_query($sql);
	foreach($results as $result) {
		$li_mois = $result->li_mois;
	}		   
	return $li_mois;	



}

